services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db
        environment:
            - DB_HOST=db
            - DEBUG=True

    db:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: hunter2