# Generated by Django 4.2.20 on 2025-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='point',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
