# Generated by Django 4.2.20 on 2025-04-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_point_options_point_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='routes.route'),
        ),
    ]
