# Generated by Django 4.2.20 on 2025-05-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameboard',
            old_name='height',
            new_name='columns',
        ),
        migrations.RenameField(
            model_name='gameboard',
            old_name='width',
            new_name='rows',
        ),
    ]
