# Generated by Django 4.2.20 on 2025-05-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='points',
            new_name='paths',
        ),
    ]
