name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install and build frontend assets
      run: |
        npm install
        npm run build

    - name: Run tests
      env:
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: hunter2
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=hunter2 postgres:13
        sleep 10
        python manage.py test